### ISSUE TITLE
1-click-bom for hp_led_switch is empty

### ISSUE THREAD

**Issue by kasbah** [BeeHive-org/BeeHive#27]
Kitspace can't deal with that yet. The BOM is completely empty, it needs at least one line. 

https://github.com/isobianin/BeeHive/blob/master/hardware/hp_led_switch/1-click-bom.csv

**Comment by amchagas** [comment]
ops! my bad. added at least two rows, can add the other items later if that is ok...

**Comment by isobianin** [comment]
My apologies, I forgot to fill in this BOM when I was finished with the layout. I will add missing components
