### ISSUE TITLE
Should kitspace page for peltier be deleted? 

### ISSUE THREAD

**Issue by kasbah** [BeeHive-org/BeeHive#34]
Since you moved it to archive... if you want to keep the page then paths in kitspace.yaml need to be updated.

**Comment by amchagas** [comment]
thanks for the heads up!
Will make the necessary changes to remove the board from kitspace

**Comment by kasbah** [comment]
Ok, I'll also add a re-direct to from the Kitspace page to https://github.com/BeeHive-org/BeeHive/tree/master/hardware/archive/peltier.
